### ISSUE TITLE
Estudar sobre aliens

### ISSUE THREAD

**Issue by eydertinoco** [eydertinoco/projectVANDER#6]
Estudar sobre aliens na cultura pop para utilizar como inspiração ao jogo.

**Comment by VanlucTeifer** [comment]
### Aliens e Imagens
- [Xenomorfo](https://i.pinimg.com/originals/ce/00/be/ce00becbce4c9cbcc5bbe61e4b1d9e7c.jpg) 
- [Alien cabeçudo, cinza, pequeno e muito inteligente](https://th.bing.com/th/id/OIP.xiKaeI4c44F1-_37R7r0JgHaEK?rs=1&pid=ImgDetMain)
- [Predador](https://th.bing.com/th/id/OIP.PQ_5KEHv9QCTTbuCl3jXcQHaLE?rs=1&pid=ImgDetMain)

**Comment by eydertinoco** [comment]
# Aliens

## Metal Slug
![image](https://github.com/user-attachments/assets/54ace729-0939-4d51-809a-093b68d4a3af)
- Aliens expressivos com tentáculos utilizando armas como ataque
- Aliens grande com poderes oculares.
## Ben 10
![image](https://github.com/user-attachments/assets/7d36b442-cd22-4b81-886a-433c98571019)
- Há diversas referências que podem ser utilizadas.
- Aliens que possam ignorar estruturas físicas para pegar o inimigo.
- Aliens que utilizam elementos da natureza.
- Aliens de grande porte que aguente dano.
## XCOM
![image](https://github.com/user-attachments/assets/c129bb63-aee9-44bb-a56a-4848808ae4ad)
- Há diversos Aliens amadurados com armas de fogo.
- Aliens que utilizam pele humana como disfarce (Referencia ao primeiro filme dos **Homens de Preto**)
