### ISSUE TITLE
Pensar sobre inimigos

### ISSUE THREAD

**Issue by eydertinoco** [eydertinoco/projectVANDER#7]
Pensar sobre como serão os inimigos dentro do jogo, suas mecânicas, combates e inteligência.

**Comment by VanlucTeifer** [comment]
### Tipos de Alienígenas
1. Bípedes com pouca/nenhuma armadura;
2. Bípedes com armadura;
3. Mecânicos;
4. Quadrúpedes estilo cachorro;
5. Estilo Xenomorfo;
6. Estilo Predador;
7. Voador natural ou com equipamento;
8. Montado em algo parecido com cavalo;

### Mecânicas e combate
- Alguns inimigos mais inteligentes usarão armas e ficarão a distância dando disparos, alguns serão mais rápidos que outros como os voadores naturais, quadrúpedes e montados;

### Inteligência
- Os inimigos de dano físico irão até o jogador, os inimigos a distância ficarão a uma distância fixa mas dentro da tela do jogador;

**Comment by eydertinoco** [comment]
## **O parasita**
### Descrição
Pessoas humanas dominadas pelos aliens se tornando zumbis com habilidades físicas superiores buscando sempre se aproximar do jogador para atacar. Eles podem varias de acordo tipo, podendo apresentar alguns que consigam atacar a distância esticando os braços ou correr mais rápido. 
### Mecânicas
#### Parasita Normal
- Corre atrás do jogador;
- Consegue causar dano ao encostar;
- Não possui defesa ou inteligência;
#### Parasita Evoluído
- Locomove mais lento em direção ao jogador;
- Consegue modificar corpo do hospedeiro permitindo esticar seus braços de lâmina até cinco metros (Delay de uso);
- Consegue se defender;
#### Parasita Desenvolvido
- Corre mais rápido;
- Ao morrer sai do corpo humano com sua forma desenvolvida.
### Referências
> Kiseijuu: Sei no Kakuritsu (1989–1994)
> Homens de Preto (1997)
> Resident Evil 4 (2005)

## **Carrapato**
### Descrição
Aliens de infecção, são carrapatos enormes com dura casca que ataca humanos os infectados inserindo ovos dentro de seus corpos.
### Mecânicas
- O carrapato vai atacar sempre NPC's para transforma-los em parasitas.
- O carrapato é mais rápido do que humanos.
- Ele é muito frágil e um ataque do jogador o mata.
### Referências
> Starcraft (1998)
> Cloverfield (2008)
