### ISSUE TITLE
Pensar sobre tipo de armas

### ISSUE THREAD

**Issue by eydertinoco** [eydertinoco/projectVANDER#8]
Pensar no tipo de armas utilizadas pelo jogador, como será seu funcionamento e como vai funcionar.

**Comment by VanlucTeifer** [comment]
### Tipos de armas
1. Arma corpo a corpo;
2. Arma de fogo (pistola, 12, etc.);
3. Explosivos;
4. Explosivos EMP (Electromagnetic Pulse);
5. Armas corpo a corpo (alienígena);
6. Armas laser (alienígena);

### Funcionamento
1. Alcance curto, infinito, CD de ataque baixo, dano baixo em área pequena;
2. Alcance depende da arma, necessita de munição e limitado, CD depende da arma (possibilidade de adicionar recarga), dano e área depende da arma;
3. Alcance médio, limitado, CD baixo/médio, dano alto em área;
4. Alcance médio, limitado, CD baixo/médio, dano zero mas paralisa unidades mecânicas em área;
5. Alcance curto, precisa de algo parecido com bateria para funcionar, CD de ataque baixo, dano baixo/médio em área pequena;
6. Alcance longo, necessita de munição e limitado, CD menor que armas de fogo, dano médio em linha reta.

**Comment by eydertinoco** [comment]
## Corpo a corpo
Apenas uma arma corpo a corpo presente, uma lâmina ou espada que saia do exoesqueleto que o jogador utilize para dar ataque quando não tiver uma arma disponível. Causando dano sempre na frente do rosto do jogador.
### Referência
> Edge of Tomorrow (2014)

## Longa distância
Um grande arsenal com munição finita podendo ser encontrado pelo mapa de forma aleatória. Para fortalecer a lore do jogo, um drop de helicóptero com os militar avisando para o jogador a localização do novo item. A mira do tiro é a direção do mouse, onde cada tipo de arma possui efeito de tiro e dano diferente.
### Tipos de armas que pode ser utilizado
1. Pistola
2. Espingarda 
3. Rifle
4. Fuzil
5. Carabina
6. Metralhadora
7. Submetralhadora.

## Armas para mapa
A utilização de bombas para matar todos os monstros na visão do jogador.

**Comment by eydertinoco** [comment]
# Sistema Definitivo
## Armas Corpo a Corpo
### Machete
Ataque de 180
## Armas longa distância

1. Pistola
Munição infinita, delay 0.25s
2. Submetralhadora
200 munição, delay 0.1s
3. Metralhadora 
500 munição, delay 0.1s
4. Espingarda 
15 munição, delay 0.5s
5. Fuzil
180 munição, delay 0.25s
6. Rifles
10 munição, delay 1s
## Updates
### Personagem (Per
Armadura
Vida
Velocidade
### Armas
Peças de armas para melhorias
Miras,
