### ISSUE TITLE
Criar arte do personagem

### ISSUE THREAD

**Issue by eydertinoco** [eydertinoco/projectVANDER#9]

**Comment by eydertinoco** [comment]
## Arquivo Aseprite
[Warrior.zip](https://github.com/user-attachments/files/16817584/Warrior.zip)
Arquivo Aseprite do personagem principal.

### Personagem parado (idle):
![Warrior-Idle](https://github.com/user-attachments/assets/830532c5-6514-4634-b0e7-47f09c0214bd)
![Warrior-Idle-1](https://github.com/user-attachments/assets/ba51202d-ed91-41ba-82e6-e98b3e81c664)
![Warrior-Idle-2](https://github.com/user-attachments/assets/8ffc75cf-bfed-45da-9425-485cf5252b5b)
### Personagem andando (idle):
![Warrior-Sheet-Walk](https://github.com/user-attachments/assets/8025f7e8-9fe5-4b01-86d0-803603b4b89e)
![Warrior-Sheet-Walk-1](https://github.com/user-attachments/assets/fed886ab-7f62-4e34-b6c6-a061e87b8054)
![Warrior-Sheet-Walk-2](https://github.com/user-attachments/assets/7090f735-b8fb-4193-8aa1-9b5a17ebde82)

**Comment by VanlucTeifer** [comment]
Parece que o Godot não lê arquivo aseprite. Acho que precisa por todos os sprites em png para poder ler.
